# Generated by Django 4.0.3 on 2022-03-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('identitynumber', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('visa', models.CharField(default=0, max_length=100)),
                ('cvv', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.IntegerField(verbose_name=5)),
                ('kundersix', models.IntegerField(verbose_name=3)),
                ('singleroom', models.IntegerField(verbose_name=4)),
                ('doubleroom', models.IntegerField(verbose_name=2)),
                ('familyroom', models.IntegerField(verbose_name=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.customer')),
            ],
        ),
    ]
