# Generated by Django 4.0.3 on 2022-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.TextField(),
        ),
    ]
